name: miutem
description: 'Plataforma académica para estudiantes de la Universidad Tecnológica Metropolitana (UTEM)'
publish_to: none

version: 3.0.0+142

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  flutter_dotenv: ^5.1.0
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  get: ^4.6.6
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  dart_jsonwebtoken: ^2.14.1
  cloud_firestore: ^5.4.5
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  video_player: ^2.9.2
  url_launcher: ^6.3.0
  skeletonizer: ^1.4.2
  material_symbols_icons: ^4.2785.1
  collection: ^1.18.0
  extended_masked_text: ^3.0.1
  flutter_colorpicker: ^1.1.0
  get_storage: ^2.1.1
  vector_math: ^2.1.4
  dotted_border: ^2.1.0
  screenshot: ^3.0.0
  share_plus: ^10.1.2
  # Firebase
  firebase_core: ^3.7.0
  firebase_remote_config: ^5.1.4
  firebase_analytics: ^11.3.4
  # Apuntes
  sqflite: ^2.4.1
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  # Awesome-notifications LOCAL
  awesome_notifications_core: ^0.10.0
  awesome_notifications: ^0.10.0
  xpath_selector_html_parser: ^3.0.1
  html: ^0.15.5
  flutter_carousel_widget: ^3.1.0
  file_saver: ^0.2.9
  adaptive_theme: ^3.7.0
  clipboard: ^0.1.3
  # Awesome-notifications REMOTE
  # awesome_notifications_fcm: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icons/prod/icon_splash.png
    - assets/videos/login_bg.mp4
    - assets/images/login_bg.png
    - assets/images/utem_logo_color_blanco.png
    - assets/images/utem_logo_color_azul.png
    - assets/images/utem_logo_negativo.png
    - assets/images/utem_isotipo_negativo.png
    - assets/animations/monito.flr
    - assets/animations/utem.flr
    - assets/images/sibutem.jpg
    - assets/launcher_icons/prod/full_icon.png
    - assets/images/exdev_light.png
    - assets/images/exdev_dark.png
    - assets/images/exdev.png
    - assets/images/miutem_claro.png
    - assets/images/miutem_oscuro.png