// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6w8hMbd8ymECRB83CIjz1hGc1zRvgT6Y',
    appId: '1:254136807635:android:839ec8ac46707d7ae36426',
    messagingSenderId: '254136807635',
    projectId: 'miutem-dev',
    storageBucket: 'miutem-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfucPKyUIdWacywdWGMmx_Gyd2IhoNbAc',
    appId: '1:254136807635:ios:0075dda3f8c582ede36426',
    messagingSenderId: '254136807635',
    projectId: 'miutem-dev',
    storageBucket: 'miutem-dev.firebasestorage.app',
    iosBundleId: 'cl.exdev.miutem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfucPKyUIdWacywdWGMmx_Gyd2IhoNbAc',
    appId: '1:254136807635:ios:0075dda3f8c582ede36426',
    messagingSenderId: '254136807635',
    projectId: 'miutem-dev',
    storageBucket: 'miutem-dev.firebasestorage.app',
    iosBundleId: 'cl.exdev.miutem',
  );

}