import "../ios/fastlane/Fastfile"

default_platform(:ios)

platform :ios do
  desc "Compila la aplicación para iOS"
  lane :build do
    ios_build()
  end

  desc "Sube la aplicación a TestFlight (requiere IPA)"
  lane :upload do |options|
    ios_upload(
      ipa_path: options[:ipa_path]
    )
  end

  desc "Build completo y upload a TestFlight"
  lane :build_and_upload do
    ios_build()
    ios_upload()
  end
end