name: Análisis
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  analizar:
    strategy:
      matrix:
        flutter_version: [ "latest", "3.41.4" ]
    runs-on: macos-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar Flutter SDK (${{ matrix.flutter_version }})
        uses: flutter-actions/setup-flutter@v4
        with:
          cache: true
          channel: stable
          version: ${{ matrix.flutter_version }}
      - name: Instalar librerías
        run: flutter pub get
      - name: Analizar código
        run: flutter analyze --fatal-infos --fatal-warnings