name: Análisis
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  analizar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Instalar librerías
        run: flutter pub get
      - name: Analizar código
        run: flutter analyze --fatal-infos --fatal-warnings