name: Pruebas
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  probar:
    runs-on: macos-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          cache: true
          channel: stable
          version: latest
      - name: Instalar librerías
        run: flutter pub get
      - name: Ejecutar pruebas unitarias
        run: flutter test --coverage --test-randomize-ordering-seed=random
