name: Pruebas
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  probar:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        flutter_version: [ "latest", "3.41.4" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar Flutter SDK (${{ matrix.flutter_version }})
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ matrix.flutter_version }}
      - name: Instalar librerías
        run: flutter pub get
      - name: Ejecutar pruebas unitarias
        run: flutter test --coverage --test-randomize-ordering-seed=random
